### ISSUE TITLE
flutter: Could not verify:

### ISSUE THREAD

**Issue by BRLOKESH** [simolus3/f_grecaptcha#3]
flutter: Could not verify:
Instance of 'ReCaptchaNotAvailableException' at #0      FGrecaptcha.verifyWithRecaptcha (package:f_grecaptcha/f_grecaptcha.dart:32:13)
<asynchronous suspension>
#1      new LoginUIState.<anonymous closure> (package:betdip/src/ui/login_ui.dart:131:47)
#2      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:511:14)
#3      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:566:30)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:166:24)
#5      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:240:9)
#6      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:177:9)
#7      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:436:9)
#8      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
#9      PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
#10     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:221:19)
#11     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:199:22)
#12     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
#13     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
#14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
#15     _rootRunUnary (dart:async/zone.dart:1136:13)
#16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#17     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#18     _invoke1 (dart:ui/hooks.dart:233:10)
#19     _dispatchPointerDataPacket (dart:ui/hooks.dart:154:5)

**Comment by simolus3** [comment]
Are you using this on iOS? It's only available on Android devices with the Google Play services installed.

**Comment by yash365** [comment]
is the plugin available in ios ?
